; Copyright (C) 2021 Christophe Meneboeuf <christophe@xtof.info>
;
; This program is free software: you can redistribute it and/or modify
; it under the terms of the GNU General Public License as published by
; the Free Software Foundation, either version 3 of the License, or
; (at your option) any later version.
;
; This program is distributed in the hope that it will be useful,
; but WITHOUT ANY WARRANTY; without even the implied warranty of
; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
; GNU General Public License for more details.
;
; You should have received a copy of the GNU General Public License
; along with this program. If not, see <http://www.gnu.org/licenses/>.



; BEWARE: NB_LEVELS * SIZEOF_STATE_LEVEL shall not be > 256
.define SIZEOF_STATE_LEVEL 7

.define SIZEOF_CONF_LEVEL 130 ;( NB_ACTORS_MAX + 2 )
.define NB_LEVELS 3



